### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cjc7373** [NWUCA/zaobot#8]
Update on 2020/8/27
已经迁移至 go-cqhttp
- [x] 计划任务在多个 worker 时会执行多次
- [ ] QQ 上的 reply 要在 TG 上体现
- [ ] TG 向 QQ 转发, 以及 reply 的处理
- [ ] requests 请求失败的处理
- [ ] log
- [ ] 调查 QQ 无法 reply 的问题

------

- [ ] 数据库的migration，采用 Flask-SQLAlchemy 及 Flask-Migrate
    - [x] 或许可以先自己写写 migration 脚本
- [x]  转发消息至 Telegram
- [x]  使用 pipenv 管理依赖
- [x]  调查内存泄漏问题
    - 目前将自带的开发服务器更换为 gunicorn
    - 观察了两天 未发现问题
- [x] 查询所有指令列表

-----
由于 Coolq 存在着以下限制:
- 无法发送图片, 无法撤回消息 (非付费版限制)
- 无法显示引用的消息
- Linux 平台下为 wine 兼容实现

可以考虑迁移至其他 bot 框架, 如 [mirai](https://github.com/mamoe/mirai).

**Comment by nicknameNothing** [comment]
This is a test message.

**Comment by cjc7373** [comment]
test
